// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrrnrbapmbnxghcqmhuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJycm5yYmFwbWJueGdoY3FtaHV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NjY1NTcsImV4cCI6MjA3MDU0MjU1N30.Iko-lkQx5mMo81aQjHoa7jW7KHtE2lfS9MiCujOj9ho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});